eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: gateway-zuul
zuul:
  routes:
    api-a:
      serviceId: client1
      path: /api-a/**
